premiosplatzi/polls/urls.py
from django.urls import path
from . import views


app_name = "polls"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results", views.results, name="results"),
    path("<int:question_id>/vote", views.vote, name="vote"),
]

premiosplatzi/premiosplatzi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/",include("polls.urls") )
]

premiosplatzi/polls/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("Date published")

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

premiosplatzi/polls/views.py
from audioop import reverse
from urllib import request
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.all()
    return render(request, "polls/index.html", {
        "latest_question_list": latest_question_list
    })


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {
        "question": question
    })


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {
        "question": question
    })


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try: 
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            "question": question,
            "error_message": "No elegiste una respuesta"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

premiosplatzi/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id%}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h2>{{question.question_text}}</h2></legend>
    {% if error_message %}
        <p>{{error_message}}</p>
    {% endif %}
    {% for choice in question.choice_set.all  %}
        <input
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{choice.id}}"
            >
        <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label>
        <br>
    {% endfor %}
</fieldset>
<input type="submit" value="Votar">
</form>

premiosplatzi/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}        
            <li>
                <a href="{% url  'polls:detail'  question.id  %}">{{question.question_text}}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are avaliable</p>
{% endif %}

premiosplatzi/polls/templates/polls/results.html
<h2>{{question.question_text}}</h2>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} voto{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">¿Votas de nuevo?</a>